[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # These are public Firebase config values, not secrets
  VITE_FIREBASE_API_KEY = "public"
  VITE_FIREBASE_AUTH_DOMAIN = "public"
  VITE_FIREBASE_PROJECT_ID = "public"
  VITE_FIREBASE_STORAGE_BUCKET = "public"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "public"
  VITE_FIREBASE_APP_ID = "public"
  VITE_FIREBASE_MEASUREMENT_ID = "public"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
